[package]
# Semantic Versioning is used: https://semver.org/
version = "1.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarily for displaying extension info in UI
title = "text2prim"
description="Use natural language to create in Omniverse"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Function-calling"

# Keywords for the extension
keywords = ["kit", "llm", "function-calling", "NLP"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/text2prim.png"


icon = "data/modularflow.png"


[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.window.extensions" = {}
"omni.kit.commands" = {}


[[python.module]]
name = "modularflow.text2.prim"

[python.pipapi]
requirements = [
    "langchain==0.2.7",
    "langchain_community==0.2.7"]
use_online_index = true
